export const languages = [
  "ENGLISH",
  "HINDI",
  "MARATHI",
  "BENGALI"
];

export const categories = [
  "WEB_DEVELOPMENT",
  "DATA_SCIENCE",
  "ARTIFICIAL_INTELLIGENCE",
  "MACHINE_LEARNING",
  "MOBILE_DEVELOPMENT",
  "GAME_DEVELOPMENT",
  "DIGITAL_MARKETING",
  "GRAPHIC_DESIGN",
  "PERSONAL_DEVELOPMENT",
  "BUSINESS",
  "FINANCE",
  "HEALTH_AND_FITNESS",
  "PHOTOGRAPHY",
  "MUSIC",
  "LANGUAGE_LEARNING"
];
